# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

sudo: false

python:
  - 2.7
  # - 3.4  # will be deprecated for pandas
  - 3.5
  - 3.6
  # - 3.7  # develop

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - pip install --upgrade pip
  - gcc --version ; python --version ; pip --version ; pwd ; ls -l

install:
  - pip install -r requirements.txt
  - pip install "nose>=1.3.7" coverage codecov "pytest>=3.0.5" codacy-coverage

before_script:
  - mkdir results
#  - python setup.py build_ext --inplace

script:
  - nosetests -v --exe --with-doctest --with-xunit --with-coverage --cover-package=bci

after_success:
  - coverage report
